apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: exoplanets
  name: exoplanets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exoplanets
  template:
    metadata:
      labels:
        app: exoplanets
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: cockroachdb1-public
        - name: DB_NAME
          value: postgres
        - name: DB_PORT
          value: "26257"
        - name: DB_USER
          value: root
        image: quay.io/redhattraining/exoplanets:v1.0
        name: exoplanets
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
