apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  revisionHistoryLimit: 12
  replicas: 12
  selector:
    matchLabels:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - image: quay.io/redhattraining/hello-nginx:v1.0
        name: hello-world-nginx
        resources:
          limits:
            memory: 2Gi


        ports:
        - containerPort: 80
          name: http
